// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bounce.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Images               [][]byte `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Audio                []byte   `protobuf:"bytes,6,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                []byte   `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	File                 []byte   `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMessage) Reset()         { *m = GroupMessage{} }
func (m *GroupMessage) String() string { return proto.CompactTextString(m) }
func (*GroupMessage) ProtoMessage()    {}
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{0}
}

func (m *GroupMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMessage.Unmarshal(m, b)
}
func (m *GroupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMessage.Marshal(b, m, deterministic)
}
func (m *GroupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMessage.Merge(m, src)
}
func (m *GroupMessage) XXX_Size() int {
	return xxx_messageInfo_GroupMessage.Size(m)
}
func (m *GroupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMessage proto.InternalMessageInfo

func (m *GroupMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GroupMessage) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *GroupMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GroupMessage) GetImages() [][]byte {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *GroupMessage) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *GroupMessage) GetVideo() []byte {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *GroupMessage) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type SignedChatMessage struct {
	MarshalledChatMessage []byte   `protobuf:"bytes,1,opt,name=MarshalledChatMessage,proto3" json:"MarshalledChatMessage,omitempty"`
	Signature             []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SignedChatMessage) Reset()         { *m = SignedChatMessage{} }
func (m *SignedChatMessage) String() string { return proto.CompactTextString(m) }
func (*SignedChatMessage) ProtoMessage()    {}
func (*SignedChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{1}
}

func (m *SignedChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedChatMessage.Unmarshal(m, b)
}
func (m *SignedChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedChatMessage.Marshal(b, m, deterministic)
}
func (m *SignedChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedChatMessage.Merge(m, src)
}
func (m *SignedChatMessage) XXX_Size() int {
	return xxx_messageInfo_SignedChatMessage.Size(m)
}
func (m *SignedChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedChatMessage proto.InternalMessageInfo

func (m *SignedChatMessage) GetMarshalledChatMessage() []byte {
	if m != nil {
		return m.MarshalledChatMessage
	}
	return nil
}

func (m *SignedChatMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// A list of UUIDs this device knows about to share with other devices
type References struct {
	SignedChatMessages   []string `protobuf:"bytes,1,rep,name=signedChatMessages,proto3" json:"signedChatMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *References) Reset()         { *m = References{} }
func (m *References) String() string { return proto.CompactTextString(m) }
func (*References) ProtoMessage()    {}
func (*References) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{2}
}

func (m *References) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_References.Unmarshal(m, b)
}
func (m *References) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_References.Marshal(b, m, deterministic)
}
func (m *References) XXX_Merge(src proto.Message) {
	xxx_messageInfo_References.Merge(m, src)
}
func (m *References) XXX_Size() int {
	return xxx_messageInfo_References.Size(m)
}
func (m *References) XXX_DiscardUnknown() {
	xxx_messageInfo_References.DiscardUnknown(m)
}

var xxx_messageInfo_References proto.InternalMessageInfo

func (m *References) GetSignedChatMessages() []string {
	if m != nil {
		return m.SignedChatMessages
	}
	return nil
}

type Device struct {
	NetworkAddress       string   `protobuf:"bytes,1,opt,name=NetworkAddress,proto3" json:"NetworkAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{3}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

type AddDeviceToDeviceGroup struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature            *MutualDeviceSignature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AddDeviceToDeviceGroup) Reset()         { *m = AddDeviceToDeviceGroup{} }
func (m *AddDeviceToDeviceGroup) String() string { return proto.CompactTextString(m) }
func (*AddDeviceToDeviceGroup) ProtoMessage()    {}
func (*AddDeviceToDeviceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{4}
}

func (m *AddDeviceToDeviceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceToDeviceGroup.Unmarshal(m, b)
}
func (m *AddDeviceToDeviceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceToDeviceGroup.Marshal(b, m, deterministic)
}
func (m *AddDeviceToDeviceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceToDeviceGroup.Merge(m, src)
}
func (m *AddDeviceToDeviceGroup) XXX_Size() int {
	return xxx_messageInfo_AddDeviceToDeviceGroup.Size(m)
}
func (m *AddDeviceToDeviceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceToDeviceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceToDeviceGroup proto.InternalMessageInfo

func (m *AddDeviceToDeviceGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddDeviceToDeviceGroup) GetSignature() *MutualDeviceSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MutualDeviceSignature struct {
	DeviceOne                     *Device  `protobuf:"bytes,1,opt,name=deviceOne,proto3" json:"deviceOne,omitempty"`
	DeviceTwo                     *Device  `protobuf:"bytes,2,opt,name=deviceTwo,proto3" json:"deviceTwo,omitempty"`
	DeviceOneSignatureOfDeviceTwo []byte   `protobuf:"bytes,3,opt,name=deviceOneSignatureOfDeviceTwo,proto3" json:"deviceOneSignatureOfDeviceTwo,omitempty"`
	DeviceTwoSignatureOfDeviceOne []byte   `protobuf:"bytes,4,opt,name=deviceTwoSignatureOfDeviceOne,proto3" json:"deviceTwoSignatureOfDeviceOne,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *MutualDeviceSignature) Reset()         { *m = MutualDeviceSignature{} }
func (m *MutualDeviceSignature) String() string { return proto.CompactTextString(m) }
func (*MutualDeviceSignature) ProtoMessage()    {}
func (*MutualDeviceSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{5}
}

func (m *MutualDeviceSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutualDeviceSignature.Unmarshal(m, b)
}
func (m *MutualDeviceSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutualDeviceSignature.Marshal(b, m, deterministic)
}
func (m *MutualDeviceSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutualDeviceSignature.Merge(m, src)
}
func (m *MutualDeviceSignature) XXX_Size() int {
	return xxx_messageInfo_MutualDeviceSignature.Size(m)
}
func (m *MutualDeviceSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_MutualDeviceSignature.DiscardUnknown(m)
}

var xxx_messageInfo_MutualDeviceSignature proto.InternalMessageInfo

func (m *MutualDeviceSignature) GetDeviceOne() *Device {
	if m != nil {
		return m.DeviceOne
	}
	return nil
}

func (m *MutualDeviceSignature) GetDeviceTwo() *Device {
	if m != nil {
		return m.DeviceTwo
	}
	return nil
}

func (m *MutualDeviceSignature) GetDeviceOneSignatureOfDeviceTwo() []byte {
	if m != nil {
		return m.DeviceOneSignatureOfDeviceTwo
	}
	return nil
}

func (m *MutualDeviceSignature) GetDeviceTwoSignatureOfDeviceOne() []byte {
	if m != nil {
		return m.DeviceTwoSignatureOfDeviceOne
	}
	return nil
}

type User struct {
	Id                    string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                 []byte                   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	SignatureSet          []*MutualDeviceSignature `protobuf:"bytes,4,rep,name=signatureSet,proto3" json:"signatureSet,omitempty"`
	MetadataSigningDevice *Device                  `protobuf:"bytes,5,opt,name=metadataSigningDevice,proto3" json:"metadataSigningDevice,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *User) GetSignatureSet() []*MutualDeviceSignature {
	if m != nil {
		return m.SignatureSet
	}
	return nil
}

func (m *User) GetMetadataSigningDevice() *Device {
	if m != nil {
		return m.MetadataSigningDevice
	}
	return nil
}

// You've been invited to join a group
type GroupInvite struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                []byte   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Users                []*User  `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupInvite) Reset()         { *m = GroupInvite{} }
func (m *GroupInvite) String() string { return proto.CompactTextString(m) }
func (*GroupInvite) ProtoMessage()    {}
func (*GroupInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{7}
}

func (m *GroupInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInvite.Unmarshal(m, b)
}
func (m *GroupInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInvite.Marshal(b, m, deterministic)
}
func (m *GroupInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInvite.Merge(m, src)
}
func (m *GroupInvite) XXX_Size() int {
	return xxx_messageInfo_GroupInvite.Size(m)
}
func (m *GroupInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInvite.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInvite proto.InternalMessageInfo

func (m *GroupInvite) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupInvite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupInvite) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *GroupInvite) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateNotificationSettings struct {
	GroupID              string   `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Notify               bool     `protobuf:"varint,2,opt,name=notify,proto3" json:"notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNotificationSettings) Reset()         { *m = UpdateNotificationSettings{} }
func (m *UpdateNotificationSettings) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationSettings) ProtoMessage()    {}
func (*UpdateNotificationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{8}
}

func (m *UpdateNotificationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotificationSettings.Unmarshal(m, b)
}
func (m *UpdateNotificationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotificationSettings.Marshal(b, m, deterministic)
}
func (m *UpdateNotificationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotificationSettings.Merge(m, src)
}
func (m *UpdateNotificationSettings) XXX_Size() int {
	return xxx_messageInfo_UpdateNotificationSettings.Size(m)
}
func (m *UpdateNotificationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotificationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotificationSettings proto.InternalMessageInfo

func (m *UpdateNotificationSettings) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *UpdateNotificationSettings) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func init() {
	proto.RegisterType((*GroupMessage)(nil), "GroupMessage")
	proto.RegisterType((*SignedChatMessage)(nil), "SignedChatMessage")
	proto.RegisterType((*References)(nil), "References")
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*AddDeviceToDeviceGroup)(nil), "AddDeviceToDeviceGroup")
	proto.RegisterType((*MutualDeviceSignature)(nil), "MutualDeviceSignature")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*GroupInvite)(nil), "GroupInvite")
	proto.RegisterType((*UpdateNotificationSettings)(nil), "UpdateNotificationSettings")
}

func init() { proto.RegisterFile("bounce.proto", fileDescriptor_85b0a0184e40096b) }

var fileDescriptor_85b0a0184e40096b = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4b, 0x6f, 0xda, 0x40,
	0x10, 0x96, 0x79, 0x86, 0xc1, 0x8a, 0xd4, 0x55, 0x41, 0x56, 0x1f, 0x12, 0x72, 0x95, 0x8a, 0x93,
	0xa9, 0xd2, 0x9c, 0xaa, 0xf6, 0x90, 0x16, 0xa9, 0xea, 0x01, 0x22, 0x19, 0x72, 0xe9, 0xa1, 0xd2,
	0xe2, 0x1d, 0xcc, 0x0a, 0xf0, 0xa2, 0xdd, 0x35, 0xb4, 0xbf, 0xad, 0xd7, 0xfe, 0xa1, 0xfe, 0x83,
	0x6a, 0x77, 0x0d, 0x84, 0x47, 0x73, 0xc9, 0xc9, 0x33, 0xdf, 0x7c, 0xf3, 0xfa, 0x3c, 0x36, 0xf8,
	0x13, 0x91, 0x67, 0x09, 0x46, 0x2b, 0x29, 0xb4, 0x08, 0xff, 0x78, 0xe0, 0x7f, 0x95, 0x22, 0x5f,
	0x0d, 0x50, 0x29, 0x9a, 0x22, 0xb9, 0x84, 0x12, 0x67, 0x81, 0xd7, 0xf1, 0xba, 0x8d, 0xb8, 0xc4,
	0x19, 0x69, 0x43, 0x4d, 0x89, 0x5c, 0x26, 0x18, 0x94, 0x2c, 0x56, 0x78, 0xa4, 0x03, 0x4d, 0x86,
	0x4a, 0xf3, 0x8c, 0x6a, 0x2e, 0xb2, 0xa0, 0x6c, 0x83, 0x0f, 0x21, 0x42, 0xa0, 0xa2, 0xf1, 0xa7,
	0x0e, 0x2a, 0x36, 0x64, 0x6d, 0x53, 0x8d, 0x2f, 0x69, 0x8a, 0x2a, 0xa8, 0x76, 0xca, 0x5d, 0x3f,
	0x2e, 0x3c, 0xf2, 0x1c, 0xaa, 0x34, 0x67, 0x5c, 0x04, 0xb5, 0x8e, 0xd7, 0xf5, 0x63, 0xe7, 0x18,
	0x74, 0xcd, 0x19, 0x8a, 0xa0, 0xee, 0x50, 0xeb, 0x98, 0xba, 0x53, 0xbe, 0xc0, 0xe0, 0xc2, 0x82,
	0xd6, 0x0e, 0x53, 0x78, 0x36, 0xe2, 0x69, 0x86, 0xec, 0xcb, 0x8c, 0xea, 0xed, 0x2a, 0x37, 0xd0,
	0x1a, 0x50, 0xa9, 0x66, 0x74, 0xb1, 0x38, 0x08, 0xd8, 0xed, 0xfc, 0xf8, 0x7c, 0x90, 0xbc, 0x82,
	0x86, 0x29, 0x45, 0x75, 0x2e, 0xdd, 0xce, 0x7e, 0xbc, 0x07, 0xc2, 0x8f, 0x00, 0x31, 0x4e, 0x51,
	0x62, 0x96, 0xa0, 0x22, 0x11, 0x10, 0x75, 0xdc, 0x56, 0x05, 0x5e, 0xa7, 0xdc, 0x6d, 0xc4, 0x67,
	0x22, 0xe1, 0x3b, 0xa8, 0xf5, 0x71, 0xcd, 0x13, 0x24, 0x6f, 0xe1, 0x72, 0x88, 0x7a, 0x23, 0xe4,
	0xfc, 0x96, 0x31, 0x89, 0x4a, 0x15, 0x92, 0x1f, 0xa1, 0xe1, 0x0f, 0x68, 0xdf, 0x32, 0xe6, 0x92,
	0xc6, 0xc2, 0x3d, 0xed, 0xfb, 0x3a, 0x79, 0x51, 0x37, 0xd0, 0x50, 0x07, 0x73, 0x37, 0xaf, 0xdb,
	0xd1, 0x20, 0xd7, 0x39, 0x5d, 0xb8, 0xb4, 0xdd, 0x12, 0xf1, 0x9e, 0x18, 0xfe, 0xf5, 0xa0, 0x75,
	0x96, 0x44, 0xae, 0xa0, 0xc1, 0x2c, 0x74, 0x97, 0x39, 0xc5, 0x9a, 0xd7, 0xf5, 0xc8, 0x91, 0xe2,
	0x7d, 0x64, 0x4f, 0x1b, 0x6f, 0x44, 0xd1, 0xf6, 0x98, 0x36, 0xde, 0x08, 0xd2, 0x87, 0xd7, 0xbb,
	0x9c, 0x5d, 0x8f, 0xbb, 0x69, 0x7f, 0x97, 0x5a, 0xb6, 0x4a, 0x3f, 0x4e, 0xda, 0x57, 0x19, 0x6f,
	0xc4, 0x09, 0xc1, 0xcc, 0x59, 0x79, 0x58, 0xe5, 0x3f, 0xa4, 0xf0, 0xb7, 0x07, 0x95, 0x7b, 0x85,
	0xf2, 0x44, 0x42, 0x02, 0x95, 0x8c, 0x2e, 0xb7, 0x97, 0x6e, 0x6d, 0x73, 0x83, 0xf6, 0x46, 0x8b,
	0x01, 0x9d, 0x43, 0x3e, 0x80, 0xbf, 0xd3, 0x70, 0x84, 0xe6, 0xc6, 0xcb, 0x8f, 0xe8, 0x7d, 0xc0,
	0x25, 0x9f, 0xa0, 0xb5, 0x44, 0x4d, 0x19, 0xd5, 0xd4, 0x50, 0x78, 0x96, 0x3a, 0x7e, 0x50, 0x3d,
	0x54, 0xef, 0x3c, 0x2b, 0x64, 0xd0, 0xb4, 0x07, 0xf0, 0x2d, 0x5b, 0x73, 0x8d, 0x4f, 0xd8, 0xe1,
	0x25, 0x54, 0x73, 0x85, 0x52, 0x15, 0xc3, 0x57, 0x23, 0xa3, 0x49, 0xec, 0xb0, 0x70, 0x08, 0x2f,
	0xee, 0x57, 0x8c, 0x6a, 0x1c, 0x0a, 0xcd, 0xa7, 0x3c, 0xb1, 0x9f, 0xf4, 0x08, 0xb5, 0xe6, 0x59,
	0xaa, 0x48, 0x00, 0xf5, 0xd4, 0xce, 0xd0, 0x2f, 0x3a, 0x6f, 0x5d, 0xf3, 0x81, 0x67, 0x26, 0xe3,
	0x97, 0x1d, 0xe0, 0x22, 0x2e, 0xbc, 0xcf, 0x57, 0xdf, 0xdf, 0xa4, 0x5c, 0xcf, 0xf2, 0x49, 0x94,
	0x88, 0x65, 0x6f, 0x36, 0x5f, 0x51, 0x39, 0x47, 0xd9, 0x73, 0xff, 0xa2, 0x9e, 0xfd, 0x17, 0x25,
	0x62, 0x31, 0xa9, 0x59, 0xeb, 0xfd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xbb, 0x48, 0xad,
	0xa5, 0x04, 0x00, 0x00,
}
