// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bounce.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Errors struct {
	All                  []string `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Errors) Reset()         { *m = Errors{} }
func (m *Errors) String() string { return proto.CompactTextString(m) }
func (*Errors) ProtoMessage()    {}
func (*Errors) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{0}
}

func (m *Errors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Errors.Unmarshal(m, b)
}
func (m *Errors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Errors.Marshal(b, m, deterministic)
}
func (m *Errors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Errors.Merge(m, src)
}
func (m *Errors) XXX_Size() int {
	return xxx_messageInfo_Errors.Size(m)
}
func (m *Errors) XXX_DiscardUnknown() {
	xxx_messageInfo_Errors.DiscardUnknown(m)
}

var xxx_messageInfo_Errors proto.InternalMessageInfo

func (m *Errors) GetAll() []string {
	if m != nil {
		return m.All
	}
	return nil
}

type ChatMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Test                 string   `protobuf:"bytes,4,opt,name=test,proto3" json:"test,omitempty"`
	Images               [][]byte `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Audio                []byte   `protobuf:"bytes,6,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                []byte   `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	File                 []byte   `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{1}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChatMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ChatMessage) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *ChatMessage) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

func (m *ChatMessage) GetImages() [][]byte {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *ChatMessage) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *ChatMessage) GetVideo() []byte {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *ChatMessage) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type SignedChatMessage struct {
	MarshalledChatMessage []byte   `protobuf:"bytes,1,opt,name=MarshalledChatMessage,proto3" json:"MarshalledChatMessage,omitempty"`
	Signature             []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SignedChatMessage) Reset()         { *m = SignedChatMessage{} }
func (m *SignedChatMessage) String() string { return proto.CompactTextString(m) }
func (*SignedChatMessage) ProtoMessage()    {}
func (*SignedChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{2}
}

func (m *SignedChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedChatMessage.Unmarshal(m, b)
}
func (m *SignedChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedChatMessage.Marshal(b, m, deterministic)
}
func (m *SignedChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedChatMessage.Merge(m, src)
}
func (m *SignedChatMessage) XXX_Size() int {
	return xxx_messageInfo_SignedChatMessage.Size(m)
}
func (m *SignedChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedChatMessage proto.InternalMessageInfo

func (m *SignedChatMessage) GetMarshalledChatMessage() []byte {
	if m != nil {
		return m.MarshalledChatMessage
	}
	return nil
}

func (m *SignedChatMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Device struct {
	NetworkAddress       string   `protobuf:"bytes,1,opt,name=NetworkAddress,proto3" json:"NetworkAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{3}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

type AddDeviceToDeviceGroup struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature            *MutualDeviceSignature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AddDeviceToDeviceGroup) Reset()         { *m = AddDeviceToDeviceGroup{} }
func (m *AddDeviceToDeviceGroup) String() string { return proto.CompactTextString(m) }
func (*AddDeviceToDeviceGroup) ProtoMessage()    {}
func (*AddDeviceToDeviceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{4}
}

func (m *AddDeviceToDeviceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceToDeviceGroup.Unmarshal(m, b)
}
func (m *AddDeviceToDeviceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceToDeviceGroup.Marshal(b, m, deterministic)
}
func (m *AddDeviceToDeviceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceToDeviceGroup.Merge(m, src)
}
func (m *AddDeviceToDeviceGroup) XXX_Size() int {
	return xxx_messageInfo_AddDeviceToDeviceGroup.Size(m)
}
func (m *AddDeviceToDeviceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceToDeviceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceToDeviceGroup proto.InternalMessageInfo

func (m *AddDeviceToDeviceGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddDeviceToDeviceGroup) GetSignature() *MutualDeviceSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MutualDeviceSignature struct {
	DeviceOne                     *Device  `protobuf:"bytes,1,opt,name=deviceOne,proto3" json:"deviceOne,omitempty"`
	DeviceTwo                     *Device  `protobuf:"bytes,2,opt,name=deviceTwo,proto3" json:"deviceTwo,omitempty"`
	DeviceOneSignatureOfDeviceTwo []byte   `protobuf:"bytes,3,opt,name=deviceOneSignatureOfDeviceTwo,proto3" json:"deviceOneSignatureOfDeviceTwo,omitempty"`
	DeviceTwoSignatureOfDeviceOne []byte   `protobuf:"bytes,4,opt,name=deviceTwoSignatureOfDeviceOne,proto3" json:"deviceTwoSignatureOfDeviceOne,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *MutualDeviceSignature) Reset()         { *m = MutualDeviceSignature{} }
func (m *MutualDeviceSignature) String() string { return proto.CompactTextString(m) }
func (*MutualDeviceSignature) ProtoMessage()    {}
func (*MutualDeviceSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{5}
}

func (m *MutualDeviceSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutualDeviceSignature.Unmarshal(m, b)
}
func (m *MutualDeviceSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutualDeviceSignature.Marshal(b, m, deterministic)
}
func (m *MutualDeviceSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutualDeviceSignature.Merge(m, src)
}
func (m *MutualDeviceSignature) XXX_Size() int {
	return xxx_messageInfo_MutualDeviceSignature.Size(m)
}
func (m *MutualDeviceSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_MutualDeviceSignature.DiscardUnknown(m)
}

var xxx_messageInfo_MutualDeviceSignature proto.InternalMessageInfo

func (m *MutualDeviceSignature) GetDeviceOne() *Device {
	if m != nil {
		return m.DeviceOne
	}
	return nil
}

func (m *MutualDeviceSignature) GetDeviceTwo() *Device {
	if m != nil {
		return m.DeviceTwo
	}
	return nil
}

func (m *MutualDeviceSignature) GetDeviceOneSignatureOfDeviceTwo() []byte {
	if m != nil {
		return m.DeviceOneSignatureOfDeviceTwo
	}
	return nil
}

func (m *MutualDeviceSignature) GetDeviceTwoSignatureOfDeviceOne() []byte {
	if m != nil {
		return m.DeviceTwoSignatureOfDeviceOne
	}
	return nil
}

type DeviceGroupIntroduction struct {
	Id                    string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                 []byte                   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	SignatureSet          []*MutualDeviceSignature `protobuf:"bytes,4,rep,name=signatureSet,proto3" json:"signatureSet,omitempty"`
	MetadataSigningDevice *Device                  `protobuf:"bytes,5,opt,name=metadataSigningDevice,proto3" json:"metadataSigningDevice,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *DeviceGroupIntroduction) Reset()         { *m = DeviceGroupIntroduction{} }
func (m *DeviceGroupIntroduction) String() string { return proto.CompactTextString(m) }
func (*DeviceGroupIntroduction) ProtoMessage()    {}
func (*DeviceGroupIntroduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{6}
}

func (m *DeviceGroupIntroduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceGroupIntroduction.Unmarshal(m, b)
}
func (m *DeviceGroupIntroduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceGroupIntroduction.Marshal(b, m, deterministic)
}
func (m *DeviceGroupIntroduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceGroupIntroduction.Merge(m, src)
}
func (m *DeviceGroupIntroduction) XXX_Size() int {
	return xxx_messageInfo_DeviceGroupIntroduction.Size(m)
}
func (m *DeviceGroupIntroduction) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceGroupIntroduction.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceGroupIntroduction proto.InternalMessageInfo

func (m *DeviceGroupIntroduction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeviceGroupIntroduction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceGroupIntroduction) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *DeviceGroupIntroduction) GetSignatureSet() []*MutualDeviceSignature {
	if m != nil {
		return m.SignatureSet
	}
	return nil
}

func (m *DeviceGroupIntroduction) GetMetadataSigningDevice() *Device {
	if m != nil {
		return m.MetadataSigningDevice
	}
	return nil
}

// You've been invited to join a group
type GroupInvite struct {
	Id                       string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                    []byte                     `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	DeviceGroupIntroductions []*DeviceGroupIntroduction `protobuf:"bytes,4,rep,name=deviceGroupIntroductions,proto3" json:"deviceGroupIntroductions,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *GroupInvite) Reset()         { *m = GroupInvite{} }
func (m *GroupInvite) String() string { return proto.CompactTextString(m) }
func (*GroupInvite) ProtoMessage()    {}
func (*GroupInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_85b0a0184e40096b, []int{7}
}

func (m *GroupInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInvite.Unmarshal(m, b)
}
func (m *GroupInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInvite.Marshal(b, m, deterministic)
}
func (m *GroupInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInvite.Merge(m, src)
}
func (m *GroupInvite) XXX_Size() int {
	return xxx_messageInfo_GroupInvite.Size(m)
}
func (m *GroupInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInvite.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInvite proto.InternalMessageInfo

func (m *GroupInvite) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupInvite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupInvite) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *GroupInvite) GetDeviceGroupIntroductions() []*DeviceGroupIntroduction {
	if m != nil {
		return m.DeviceGroupIntroductions
	}
	return nil
}

func init() {
	proto.RegisterType((*Errors)(nil), "Errors")
	proto.RegisterType((*ChatMessage)(nil), "ChatMessage")
	proto.RegisterType((*SignedChatMessage)(nil), "SignedChatMessage")
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*AddDeviceToDeviceGroup)(nil), "AddDeviceToDeviceGroup")
	proto.RegisterType((*MutualDeviceSignature)(nil), "MutualDeviceSignature")
	proto.RegisterType((*DeviceGroupIntroduction)(nil), "DeviceGroupIntroduction")
	proto.RegisterType((*GroupInvite)(nil), "GroupInvite")
}

func init() { proto.RegisterFile("bounce.proto", fileDescriptor_85b0a0184e40096b) }

var fileDescriptor_85b0a0184e40096b = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x8e, 0xda, 0x30,
	0x10, 0x6d, 0x08, 0x84, 0x32, 0x44, 0xa8, 0xb5, 0x0a, 0xb5, 0x56, 0xad, 0x84, 0x52, 0x6d, 0x45,
	0x2f, 0xa1, 0x62, 0xf7, 0x54, 0xa9, 0x87, 0xdd, 0x52, 0x55, 0x3d, 0xd0, 0x95, 0xb2, 0x9c, 0x7a,
	0xa8, 0x64, 0x62, 0x6f, 0xb0, 0x08, 0x31, 0xb2, 0x1d, 0xf8, 0x9a, 0x7e, 0x4d, 0xef, 0xfd, 0x97,
	0xfe, 0x41, 0x15, 0x3b, 0x0b, 0x81, 0x85, 0xbd, 0xec, 0x29, 0x33, 0x6f, 0xde, 0x8c, 0x3d, 0x2f,
	0xe3, 0x01, 0x7f, 0x26, 0xf2, 0x2c, 0x66, 0xe1, 0x4a, 0x0a, 0x2d, 0x82, 0x33, 0xf0, 0xbe, 0x4a,
	0x29, 0xa4, 0x42, 0x2f, 0xc0, 0x25, 0x69, 0x8a, 0x9d, 0xbe, 0x3b, 0x68, 0x45, 0x85, 0x19, 0xfc,
	0x71, 0xa0, 0xfd, 0x65, 0x4e, 0xf4, 0x84, 0x29, 0x45, 0x12, 0x86, 0x3a, 0x50, 0xe3, 0x14, 0x3b,
	0x7d, 0x67, 0xd0, 0x8a, 0x6a, 0x9c, 0xa2, 0x1e, 0x78, 0x4a, 0xe4, 0x32, 0x66, 0xb8, 0x66, 0xb0,
	0xd2, 0x43, 0x7d, 0x68, 0x53, 0xa6, 0x34, 0xcf, 0x88, 0xe6, 0x22, 0xc3, 0xae, 0x09, 0x56, 0x21,
	0x84, 0xa0, 0xae, 0x99, 0xd2, 0xb8, 0x6e, 0x42, 0xc6, 0x2e, 0xaa, 0xf1, 0x25, 0x49, 0x98, 0xc2,
	0x8d, 0xbe, 0x3b, 0xf0, 0xa3, 0xd2, 0x43, 0xaf, 0xa0, 0x41, 0x72, 0xca, 0x05, 0xf6, 0xfa, 0xce,
	0xc0, 0x8f, 0xac, 0x53, 0xa0, 0x6b, 0x4e, 0x99, 0xc0, 0x4d, 0x8b, 0x1a, 0xa7, 0xa8, 0x7b, 0xc7,
	0x53, 0x86, 0x9f, 0x1b, 0xd0, 0xd8, 0x41, 0x02, 0x2f, 0x6f, 0x79, 0x92, 0x31, 0x5a, 0x6d, 0xe5,
	0x12, 0xba, 0x13, 0x22, 0xd5, 0x9c, 0xa4, 0xe9, 0x5e, 0xc0, 0x74, 0xe7, 0x47, 0xc7, 0x83, 0xe8,
	0x0d, 0xb4, 0x8a, 0x52, 0x44, 0xe7, 0xd2, 0xf6, 0xec, 0x47, 0x3b, 0x20, 0xf8, 0x08, 0xde, 0x98,
	0xad, 0x79, 0xcc, 0xd0, 0x7b, 0xe8, 0xfc, 0x60, 0x7a, 0x23, 0xe4, 0xe2, 0x8a, 0x52, 0xc9, 0x94,
	0x2a, 0x45, 0x3b, 0x40, 0x83, 0x5f, 0xd0, 0xbb, 0xa2, 0xd4, 0x26, 0x4d, 0x85, 0xfd, 0x7e, 0x93,
	0x22, 0x5f, 0x3d, 0x90, 0xfa, 0x12, 0x5a, 0x6a, 0xef, 0xe4, 0xf6, 0xa8, 0x17, 0x4e, 0x72, 0x9d,
	0x93, 0xd4, 0xa6, 0x6d, 0xaf, 0x11, 0xed, 0x88, 0xc1, 0x3f, 0x07, 0xba, 0x47, 0x49, 0xe8, 0x1c,
	0x5a, 0xd4, 0x40, 0x37, 0x99, 0xed, 0xb9, 0x3d, 0x6a, 0x86, 0x96, 0x14, 0xed, 0x22, 0x3b, 0xda,
	0x74, 0x23, 0xca, 0x63, 0x0f, 0x69, 0xd3, 0x8d, 0x40, 0x63, 0x78, 0xbb, 0xcd, 0xd9, 0x9e, 0x71,
	0x73, 0x37, 0xde, 0xa6, 0xba, 0x46, 0xab, 0xc7, 0x49, 0xbb, 0x2a, 0xd3, 0x8d, 0x78, 0x40, 0x28,
	0xee, 0x59, 0xaf, 0x56, 0x39, 0x41, 0x0a, 0xfe, 0x3a, 0xf0, 0xba, 0xa2, 0xe4, 0xf7, 0x4c, 0x4b,
	0x41, 0xf3, 0xd8, 0x8c, 0xdd, 0xa1, 0xaa, 0x08, 0xea, 0x19, 0x59, 0xde, 0x8f, 0xaf, 0xb1, 0x8b,
	0xc1, 0x32, 0x83, 0x57, 0xde, 0xd9, 0x3a, 0xe8, 0x13, 0xf8, 0x5b, 0x59, 0x6f, 0x59, 0x31, 0xb8,
	0xee, 0x23, 0xbf, 0x60, 0x8f, 0x8b, 0x3e, 0x43, 0x77, 0xc9, 0x34, 0xa1, 0x44, 0x93, 0x82, 0xc2,
	0xb3, 0xc4, 0xf2, 0x71, 0x63, 0x5f, 0xd0, 0xe3, 0xac, 0xe0, 0xb7, 0x03, 0xed, 0xb2, 0x95, 0x35,
	0xd7, 0xec, 0x09, 0x4d, 0x4c, 0x01, 0xd3, 0xe3, 0xca, 0xa8, 0xb2, 0x21, 0x1c, 0x9e, 0x90, 0x2e,
	0x3a, 0x99, 0x39, 0xba, 0x00, 0xef, 0xda, 0x6c, 0x14, 0xf4, 0x01, 0x3a, 0x11, 0x8b, 0x19, 0x5f,
	0xb3, 0xfb, 0x07, 0xe3, 0x87, 0x95, 0xe7, 0x73, 0xd6, 0x0c, 0xed, 0xaa, 0x09, 0x9e, 0x5d, 0x9f,
	0xff, 0x7c, 0x97, 0x70, 0x3d, 0xcf, 0x67, 0x61, 0x2c, 0x96, 0xc3, 0xf9, 0x62, 0x45, 0xe4, 0x82,
	0xc9, 0xa1, 0x5d, 0x4d, 0x43, 0xb3, 0x9a, 0x62, 0x91, 0xce, 0x3c, 0x63, 0x5d, 0xfc, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x07, 0x95, 0x0c, 0x52, 0xb4, 0x04, 0x00, 0x00,
}
