// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BounceClient is the client API for Bounce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BounceClient interface {
	ReceiveMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Errors, error)
}

type bounceClient struct {
	cc grpc.ClientConnInterface
}

func NewBounceClient(cc grpc.ClientConnInterface) BounceClient {
	return &bounceClient{cc}
}

func (c *bounceClient) ReceiveMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Errors, error) {
	out := new(Errors)
	err := c.cc.Invoke(ctx, "/Bounce/ReceiveMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BounceServer is the server API for Bounce service.
// All implementations must embed UnimplementedBounceServer
// for forward compatibility
type BounceServer interface {
	ReceiveMessage(context.Context, *ChatMessage) (*Errors, error)
	mustEmbedUnimplementedBounceServer()
}

// UnimplementedBounceServer must be embedded to have forward compatible implementations.
type UnimplementedBounceServer struct {
}

func (UnimplementedBounceServer) ReceiveMessage(context.Context, *ChatMessage) (*Errors, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMessage not implemented")
}
func (UnimplementedBounceServer) mustEmbedUnimplementedBounceServer() {}

// UnsafeBounceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BounceServer will
// result in compilation errors.
type UnsafeBounceServer interface {
	mustEmbedUnimplementedBounceServer()
}

func RegisterBounceServer(s grpc.ServiceRegistrar, srv BounceServer) {
	s.RegisterService(&Bounce_ServiceDesc, srv)
}

func _Bounce_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bounce/ReceiveMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceServer).ReceiveMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Bounce_ServiceDesc is the grpc.ServiceDesc for Bounce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bounce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bounce",
	HandlerType: (*BounceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _Bounce_ReceiveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bounce.proto",
}
