// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: bounce.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Errors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All []string `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *Errors) Reset() {
	*x = Errors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Errors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Errors) ProtoMessage() {}

func (x *Errors) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Errors.ProtoReflect.Descriptor instead.
func (*Errors) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{0}
}

func (x *Errors) GetAll() []string {
	if x != nil {
		return x.All
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source      string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"` // Group UUID or DM
	Test        string   `protobuf:"bytes,4,opt,name=test,proto3" json:"test,omitempty"`
	Images      [][]byte `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Audio       []byte   `protobuf:"bytes,6,opt,name=audio,proto3" json:"audio,omitempty"`
	Video       []byte   `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	File        []byte   `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ChatMessage) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ChatMessage) GetTest() string {
	if x != nil {
		return x.Test
	}
	return ""
}

func (x *ChatMessage) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ChatMessage) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ChatMessage) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *ChatMessage) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type SignedChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarshalledChatMessage []byte `protobuf:"bytes,1,opt,name=MarshalledChatMessage,proto3" json:"MarshalledChatMessage,omitempty"`
	Signature             []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"` //sig(SHA3(message))
}

func (x *SignedChatMessage) Reset() {
	*x = SignedChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedChatMessage) ProtoMessage() {}

func (x *SignedChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedChatMessage.ProtoReflect.Descriptor instead.
func (*SignedChatMessage) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{2}
}

func (x *SignedChatMessage) GetMarshalledChatMessage() []byte {
	if x != nil {
		return x.MarshalledChatMessage
	}
	return nil
}

func (x *SignedChatMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkAddress string `protobuf:"bytes,1,opt,name=NetworkAddress,proto3" json:"NetworkAddress,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{3}
}

func (x *Device) GetNetworkAddress() string {
	if x != nil {
		return x.NetworkAddress
	}
	return ""
}

type AddDeviceToDeviceGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature *MutualDeviceSignature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *AddDeviceToDeviceGroup) Reset() {
	*x = AddDeviceToDeviceGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDeviceToDeviceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceToDeviceGroup) ProtoMessage() {}

func (x *AddDeviceToDeviceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceToDeviceGroup.ProtoReflect.Descriptor instead.
func (*AddDeviceToDeviceGroup) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{4}
}

func (x *AddDeviceToDeviceGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddDeviceToDeviceGroup) GetSignature() *MutualDeviceSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MutualDeviceSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceOne                     *Device `protobuf:"bytes,1,opt,name=deviceOne,proto3" json:"deviceOne,omitempty"`
	DeviceTwo                     *Device `protobuf:"bytes,2,opt,name=deviceTwo,proto3" json:"deviceTwo,omitempty"`
	DeviceOneSignatureOfDeviceTwo []byte  `protobuf:"bytes,3,opt,name=deviceOneSignatureOfDeviceTwo,proto3" json:"deviceOneSignatureOfDeviceTwo,omitempty"`
	DeviceTwoSignatureOfDeviceOne []byte  `protobuf:"bytes,4,opt,name=deviceTwoSignatureOfDeviceOne,proto3" json:"deviceTwoSignatureOfDeviceOne,omitempty"`
}

func (x *MutualDeviceSignature) Reset() {
	*x = MutualDeviceSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MutualDeviceSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutualDeviceSignature) ProtoMessage() {}

func (x *MutualDeviceSignature) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutualDeviceSignature.ProtoReflect.Descriptor instead.
func (*MutualDeviceSignature) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{5}
}

func (x *MutualDeviceSignature) GetDeviceOne() *Device {
	if x != nil {
		return x.DeviceOne
	}
	return nil
}

func (x *MutualDeviceSignature) GetDeviceTwo() *Device {
	if x != nil {
		return x.DeviceTwo
	}
	return nil
}

func (x *MutualDeviceSignature) GetDeviceOneSignatureOfDeviceTwo() []byte {
	if x != nil {
		return x.DeviceOneSignatureOfDeviceTwo
	}
	return nil
}

func (x *MutualDeviceSignature) GetDeviceTwoSignatureOfDeviceOne() []byte {
	if x != nil {
		return x.DeviceTwoSignatureOfDeviceOne
	}
	return nil
}

type DeviceGroupIntroduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                 []byte                   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	SignatureSet          []*MutualDeviceSignature `protobuf:"bytes,4,rep,name=signatureSet,proto3" json:"signatureSet,omitempty"`
	MetadataSigningDevice *Device                  `protobuf:"bytes,5,opt,name=metadataSigningDevice,proto3" json:"metadataSigningDevice,omitempty"`
}

func (x *DeviceGroupIntroduction) Reset() {
	*x = DeviceGroupIntroduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceGroupIntroduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceGroupIntroduction) ProtoMessage() {}

func (x *DeviceGroupIntroduction) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceGroupIntroduction.ProtoReflect.Descriptor instead.
func (*DeviceGroupIntroduction) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceGroupIntroduction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceGroupIntroduction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceGroupIntroduction) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *DeviceGroupIntroduction) GetSignatureSet() []*MutualDeviceSignature {
	if x != nil {
		return x.SignatureSet
	}
	return nil
}

func (x *DeviceGroupIntroduction) GetMetadataSigningDevice() *Device {
	if x != nil {
		return x.MetadataSigningDevice
	}
	return nil
}

// You've been invited to join a group
type GroupInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                    []byte                     `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	DeviceGroupIntroductions []*DeviceGroupIntroduction `protobuf:"bytes,4,rep,name=deviceGroupIntroductions,proto3" json:"deviceGroupIntroductions,omitempty"`
}

func (x *GroupInvite) Reset() {
	*x = GroupInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bounce_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInvite) ProtoMessage() {}

func (x *GroupInvite) ProtoReflect() protoreflect.Message {
	mi := &file_bounce_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInvite.ProtoReflect.Descriptor instead.
func (*GroupInvite) Descriptor() ([]byte, []int) {
	return file_bounce_proto_rawDescGZIP(), []int{7}
}

func (x *GroupInvite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupInvite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInvite) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GroupInvite) GetDeviceGroupIntroductions() []*DeviceGroupIntroduction {
	if x != nil {
		return x.DeviceGroupIntroductions
	}
	return nil
}

var File_bounce_proto protoreflect.FileDescriptor

var file_bounce_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a,
	0x0a, 0x06, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x22, 0xc3, 0x01, 0x0a, 0x0b, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0x67, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x4d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x15, 0x4d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5e, 0x0a, 0x16, 0x41,
	0x64, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x75, 0x74, 0x75, 0x61,
	0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xf1, 0x01, 0x0a, 0x15,
	0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x25, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x77, 0x6f, 0x12, 0x44, 0x0a, 0x1d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f, 0x66, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x77, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x1d, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x6e, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f, 0x66,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x77, 0x6f, 0x12, 0x44, 0x0a, 0x1d, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x77, 0x6f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f,
	0x66, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x1d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x77, 0x6f, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x4f, 0x66, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x22,
	0xce, 0x01, 0x0a, 0x17, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x53, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x75,
	0x74, 0x75, 0x61, 0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53, 0x65,
	0x74, 0x12, 0x3d, 0x0a, 0x15, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53, 0x69, 0x67,
	0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x15, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x54, 0x0a, 0x18, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x18, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x32, 0x33, 0x0a, 0x06, 0x42, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x0e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x07, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6b, 0x70, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x62, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bounce_proto_rawDescOnce sync.Once
	file_bounce_proto_rawDescData = file_bounce_proto_rawDesc
)

func file_bounce_proto_rawDescGZIP() []byte {
	file_bounce_proto_rawDescOnce.Do(func() {
		file_bounce_proto_rawDescData = protoimpl.X.CompressGZIP(file_bounce_proto_rawDescData)
	})
	return file_bounce_proto_rawDescData
}

var file_bounce_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bounce_proto_goTypes = []interface{}{
	(*Errors)(nil),                  // 0: Errors
	(*ChatMessage)(nil),             // 1: ChatMessage
	(*SignedChatMessage)(nil),       // 2: SignedChatMessage
	(*Device)(nil),                  // 3: Device
	(*AddDeviceToDeviceGroup)(nil),  // 4: AddDeviceToDeviceGroup
	(*MutualDeviceSignature)(nil),   // 5: MutualDeviceSignature
	(*DeviceGroupIntroduction)(nil), // 6: DeviceGroupIntroduction
	(*GroupInvite)(nil),             // 7: GroupInvite
}
var file_bounce_proto_depIdxs = []int32{
	5, // 0: AddDeviceToDeviceGroup.signature:type_name -> MutualDeviceSignature
	3, // 1: MutualDeviceSignature.deviceOne:type_name -> Device
	3, // 2: MutualDeviceSignature.deviceTwo:type_name -> Device
	5, // 3: DeviceGroupIntroduction.signatureSet:type_name -> MutualDeviceSignature
	3, // 4: DeviceGroupIntroduction.metadataSigningDevice:type_name -> Device
	6, // 5: GroupInvite.deviceGroupIntroductions:type_name -> DeviceGroupIntroduction
	1, // 6: Bounce.ReceiveMessage:input_type -> ChatMessage
	0, // 7: Bounce.ReceiveMessage:output_type -> Errors
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bounce_proto_init() }
func file_bounce_proto_init() {
	if File_bounce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bounce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Errors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bounce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bounce_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bounce_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bounce_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDeviceToDeviceGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bounce_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MutualDeviceSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bounce_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceGroupIntroduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bounce_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bounce_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bounce_proto_goTypes,
		DependencyIndexes: file_bounce_proto_depIdxs,
		MessageInfos:      file_bounce_proto_msgTypes,
	}.Build()
	File_bounce_proto = out.File
	file_bounce_proto_rawDesc = nil
	file_bounce_proto_goTypes = nil
	file_bounce_proto_depIdxs = nil
}
